# HTTP-server listen address
ListenAddress = "http://0.0.0.0:8000"

# File storage path
StoragePath = "/var/lib/simplefileshare"

# File removing period (hours)
RemoveFilePeriod = 1

LogLevel = "error"
